name: Main CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java (for Android)
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.1"

      - name: Setup Derry
        run: |
          flutter pub global activate derry
          echo "/opt/hostedtoolcache/flutter/2.0.1-stable/x64/.pub-cache/bin" >> $GITHUB_PATH

      - name: Build App
        run: derry build

      - name: Build APK
        run: flutter build apk --dart-define=ci=true

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
