name: PR title linting
on:
  pull_request:
    branches: [ master ]
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '([a-z])+\: ([a-z1-9])+'
        allowed_prefixes: 'style,feat,fix,refactor,ci,chore'
        prefix_case_sensitive: true
        min_length: 5
        max_length: 72
        github_token: ${{ github.token }}
